external/hash/unaligned.h

The unalignedread_le32toh macro is incorrectly makred as
unalignedread_le64toh and the correct 64 bit version follows afterwards.

unaligned_read_le32toh is makred as 64bit version.

---

CMakeLists.txt

If the build system doesn't have a C++ compiler installed, CMake will fail
with a line like:
Check for working CXX compiler: CMAKE_CXX_COMPILER_FULLPATH-NOTFOUND
As flatcc is explicitly C-only, let's be sure we can use it without a C++
compiler installed.
Signed-off-by: Steve deRosier <steve.derosier@lairdtech.com>

build: Specify C language explicitly for CMake

---

include/flatcc/flatcc_json_parser.h
src/compiler/codegen_c_json_parser.c

I've started playing with flatcc with simple schemes, and found that when there are no global enums defined generated json parser is uncompilable. Then, it was unable to parse input containing empty objects or arrays ( {}, [] ). Wasn't too hard to fix :)

Fixes in JSON parser

---

CMakeLists.txt
test/json_test/test_json.c
test/monster_test/monster_test.fbs

Added option FLATCC_COVERAGE, which is OFF by default. It can be turned on only in debug build with tests enabled, and is useful only with gcc compiler. When turned on it enables generation of coverage information during build and run. It also adds "coverage" build target, which collects data saved during test runs and makes useful html reports. Related to #19

Added coverage target to enable coverage testing with gcov/lcov

---

src/compiler/codegen_c_reader.c
test/monster_test/monster_test.c

- wrapped generation of find/scan function in macro
- added tests for scan_range
- added scan_next and tests for it
Unfortunately, it's not possible to wrap defines for default keys in macro as is (at least I don't know any way to add define into define), I see here two possibilities:
1. Make wrapper function which generate all those defines to reduce duplication in codegen
2. Switch from plain defines to inline functions so that they can be enclosed in macro
Also it might be a good idea to merge gen_find and gen_scan into one bigger gen_search, and merge various define_find/scan* into corresponding define_search*.

Various improvements to scan functionality and tests

---

src/compiler/codegen_c_json_parser.c
test/json_test/test_json.c

Sometimes when failing to parse table parser crashes in flatcc_builder_end_table (failing check for some frame), so I added a quick fix to early out in this case. This definitely should be investigated further, but for now I'm out of ideas, and somewhat short of time. 
As for your comment on checking for error_line instead of expected_error - I think that both checks could be useful. Anyway, if you don't like current implementation you can just drop testing commit and accept fix only.

Quick fix for rare JSON parser cras when unexpected field encountered

---

test/json_test/test_json.c

Actually not a lot of new tests, but fixed typos in old ones that allowed them to pass. Now these tests pass since quick fix is still in effect, but if you comment [this](https://github.com/dvidelabs/flatcc/blob/master/src/compiler/codegen_c_json_parser.c#L565) line, then test will enter endless loop starting [there](https://github.com/dvidelabs/flatcc/commit/4d82573ea2f8a927b21c85e8677074d2f033cd7a#diff-9049181caf7ad9479b155c9c554775e2R199).

More tests

---

config/config.h
include/flatcc/flatcc.h
src/compiler/codegen_c_reader.c
src/compiler/flatcc.c
test/monster_test/monster_test.c

We discussed possibility of adding scan functions for all fields as a default option and I tried to implement it.  I also tried in my project to remove keys from fields, regenerate headers with new flatcc and measure compilation time on my laptop. After several clean runs of "time make all" it became apparent that there is no noticeable effect on compilation time (7.5 sec before and after on average) nor binaries size (514K executable compiled in debug mode). Reader header size became even smaller (21K before, 20K after).

Allow to generate scan for all fields as a default option

---

scripts/initbuild.sh

`make` failure on Ubuntu 16.04.

fix: fail mkdir

---

include/flatcc/flatcc_json_parser.h
src/compiler/codegen_c_builder.c
src/compiler/codegen_c_json_parser.c
src/compiler/codegen_c_reader.c

The code generated by flatcc could not be compiled cleanly with
C++ compilers, for the following reasons:
* C++ does not allow implicit casts from `void *` to
`destination *`. Addressed by adding explicit type-casts where
such type-conversions occur, or by adding additional type
information to source types.
* C++ deprecates implicit casts from string constants to char *'s,
or to char array types. Addressed by modifying the constant
exposed by the `%s_identifier` macros to be of the appropriate
`flatbuffers_fid_t` data type.

fix compatibility with C++ compilers.

---

src/compiler/codegen_c_builder.c
test/monster_test/monster_test.c

This fixes an issue where an additional table root was inserted just prior
to a _nest()ed flatbuffer, which of course already has its own table root.

_nest() was unnecessarily calling _buffer_start()/_buffer_end().

---

include/flatcc/flatcc_json_parser.h
include/flatcc/portable/pprintint.h
src/compiler/codegen_c_builder.c
src/runtime/json_parser.c

Silence gcc 7.x warnings about implicit fallthrough

---

include/flatcc/portable/paligned_alloc.h
include/flatcc/portable/pbase64.h

Avoid the following error when using flatcc from C++ via this PR:
```
In file included from /X/flatcc/include/flatcc/portable/pstdalign.h:60:0,
from /X/flatcc/include/flatcc/flatcc_flatbuffers.h:20,
from /X/flatcc/include/flatcc/flatcc_builder.h:64,
from /X/src/json_to_flatbuffers_converter.inl:9,
from /X/src/json_to_flatbuffers_converter.h:31,
from /X/curl_test_task.cpp:3:
/X/flatcc/include/flatcc/portable/paligned_alloc.h: In function 'void __portable_aligned_free(void*)':
/X/flatcc/include/flatcc/portable/paligned_alloc.h:131:32: error: invalid conversion from 'void*' to 'char*' [-fpermi]
char *raw = ((void **)p)[-1];
```

Add cast to (char *) to avoid -fpermissive error when using C++

---

src/compiler/codegen_c_json_parser.c

to support compiling the json_parser header with a C++ compiler.

Fix incorrect void * in generated _as_root JSON parsers

---

include/flatcc/flatcc.h
include/flatcc/flatcc_accessors.h
include/flatcc/flatcc_alloc.h
include/flatcc/flatcc_builder.h
include/flatcc/flatcc_emitter.h
include/flatcc/flatcc_endian.h
include/flatcc/flatcc_flatbuffers.h
include/flatcc/flatcc_identifier.h
include/flatcc/flatcc_iov.h
include/flatcc/flatcc_json_parser.h
include/flatcc/flatcc_json_printer.h
include/flatcc/flatcc_portable.h
include/flatcc/flatcc_rtconfig.h
include/flatcc/flatcc_types.h
include/flatcc/flatcc_unaligned.h
include/flatcc/flatcc_verifier.h
include/flatcc/flatcc_version.h
include/flatcc/support/cdump.h
include/flatcc/support/elapsed.h
include/flatcc/support/hexdump.h
include/flatcc/support/readfile.h

Wrap public header files in `#ifdef _cplusplus` guards to allow `#include`s from other C++ or C translation units.
Also add support to codegen_c sources to add include guards to all generated headers.
This helps me when using flatcc from C++, as I do not need to wrap the flatcc header includes in `extern "C"`.
As a first attempt, I added it manually to (almost all) header files in `include`, just after the existing `#ifdef FILE_H` include guards (if present). This generates files such as I modify them by hand, and for my purposes appears to work fine.

[WIP] Add '#ifdef __cplusplus' guards 

---

src/compiler/codegen_c_builder.c
src/compiler/codegen_c_reader.c

Adding these typecasts prevents the more recent versions of the clang++ compiler from complaining.

Some more typecasts to satisfy the latest version of the clang++ compiler

---

CMakeLists.txt
test/CMakeLists.txt
test/monster_test_cpp/CMakeLists.txt
test/monster_test_cpp/monster_test.cpp

This simply consists of a cpp file that includes samples/monster/monster_test.c.
This can help us detect issues like those addressed by f503a8c and cd727d0.

Added a C++ test.

---

scripts/_user_build.in

Hi,
I changed the `if` condition because it was always true: The `-eq` causes the strings to be interpreted as integers if possible.
For proper comparison of strings use `=`.
Also removed `PORTABLE` variable because it wasn't used in the whole project (correct me if I am wrong).
And finally corrected a typo.

Fix scripts/_user_build.in

---

scripts/test.sh

Hi,
I noticed that passing tests in debug mode `(scripts/test.sh --debug)` was not working properly: it passes debug and release tests instead of only the first one. In the output of the command the first line is:
`scripts/test.sh: 12: [: --debug: unexpected operator`.
This is due to the `==` operator which is s a bash-specific alias for `=` but is not supported in POSIX sh. To fix it, we need to change the shebang to use bash or use the `=` operator.
I prefer to change the operator instead of the shebang because using sh give more portability advantages.

Fix scripts/test.sh in debug mode

---

src/compiler/codegen_c.h

Hi,
Correct me if I am missing something, but I think these two `break` are necessary.

Fix switch-case statement

---

CMakeLists.txt

C++ is only used when building the tests, so only include it as a
language via project() when FLATCC_TEST is enabled. This allows
toolchains that don't have C++ to build flatcc.
Signed-off-by: Joel Carlson <JoelsonCarl@gmail.com>

CMakeLists.txt: conditionally require C++ based on FLATCC_TEST

---

src/compiler/CMakeLists.txt
src/runtime/CMakeLists.txt

Replace lib with ${lib_dir} in compiler and runtime CMakeLists.

Correct FLATCC_INSTALL_LIB bug

---

src/compiler/semantics.c

#112 when the table field in the schema has id attribute and not placed in sequence order, flatcc falls into an endless loop because of the mistake when reordering the table field with id attribute

Fix mistake when reordering the table field with id attribute

---

README.md

`flatcc -cr` only generates common_reader, but not the protocol reader. So I think `flatcc -cr --reader` to also generate protocol reader is better for introducing "Reading a Buffer".

Fix commandline in README

---

samples/monster/monster.c

Some string definitions were typed as ns(Weapon_ref_t) while they should
be flatbuffers_string_ref_t. Note that the former was also compiling &
running correctly as both ref types boil down to the same underlying ref
type.

Use the correct string ref type in monster sample

---

CMakeLists.txt
src/compiler/semantics.c

Fix the following build errors on Fedora 30:
```
src/compiler/semantics.c:702:20: error: this statement may fall through
702 |             key_ok = 0;
samples/reflection/bfbs2json.c:86:5: error: ‘%s’ directive argument is null
test/monster_test/monster_test.c:1948:5: error: ‘strncpy’ output truncated copying 5 bytes from a string of length 12
1948 |     strncpy(foobar->text, "hello, world", ns(FooBar_text_get_len()));
```
I've done zero testing of this other than it builds.

Fix misc build errors on GCC 9

---

README.md
include/flatcc/flatcc_assert.h
include/flatcc/flatcc_builder.h
include/flatcc/flatcc_flatbuffers.h
include/flatcc/flatcc_json_parser.h
src/compiler/codegen_c_builder.c
src/compiler/codegen_c_reader.c
src/runtime/builder.c
src/runtime/json_parser.c
src/runtime/json_printer.c
src/runtime/refmap.c
src/runtime/verifier.c

It would be really nice to have a possibility to provide own assert function to generated code. In Google's flatbuffers it is done by providing FLATBUFFERS_ASSERT define. Following change introduces the same mechanism for flatcc.

Custom assert definition for generated code

---

include/flatcc/flatcc_builder.h
src/runtime/builder.c

There is one unnamed union inside _**struct __flatcc_builder_frame**_ that, even when compiled with gcc _**-std=c99**_ flag, is only caught with the _**-pedantic-errors**_ flag.
This change-request simply names the union and updates instances where the _**frame()**_ macro accesses the union

Portability: fix ISO C99 unnamed struct/union

---

src/compiler/codegen_c_builder.c

I looked at adding -Wstrict-prototypes for the build, but it's already enabled in clang, which is the default compiler on my current system (and I don't have enough familiarity with CMake to quickly set up a build with a non-default compiler).  In a different project with a different build system, this particular change cleans the strict-prototypes warning for GCC, though.

fix a "-Wstrict-prototypes" warning

---

src/cli/flatcc_cli.c

"flatcc -c" without any source file doesn't produce the flatbuffers_common_builder.h header at the moment (line 430 cleared the cgen_common_builder option). Furthermore "flatcc --common_builder" mistakenly requires a source file (line 433), while it shouldn't need one. Both issues are addressed in this commit.

Fix standalone -c and --common_builder options

---

include/flatcc/support/elapsed.h

with clang-10 on ubuntu 18.04:
In file included from /root/src/flatcc/test/monster_test/monster_test.c:7:
/root/src/flatcc/include/flatcc/support/elapsed.h:19:22: error: implicit conversion from 'long' to 'double' may lose precision [-Werror,-Wimplicit-int-float-conversion]
return tv.tv_sec - t0.tv_sec + (tv.tv_usec - t0.tv_usec) / 1000000.;
~~~~~~~~~~^~~~~~~~~~~ ~
/root/src/flatcc/include/flatcc/support/elapsed.h:19:48: error: implicit conversion from 'long' to 'double' may lose precision [-Werror,-Wimplicit-int-float-conversion]
return tv.tv_sec - t0.tv_sec + (tv.tv_usec - t0.tv_usec) / 1000000.;
~~~~~~~~~~~^~~~~~~~~~~~  ~
/root/src/flatcc/include/flatcc/support/elapsed.h:51:54: error: implicit conversion from 'size_t' (aka 'unsigned long') to 'double' may lose precision …

explicitly convert to double to suppress warnings

---

samples/reflection/bfbs2json.c
src/compiler/catalog.h
src/compiler/codegen_schema.c
test/reflection_test/reflection_test.c

The sample bfbs2json was ignoring services present in BFBS
files generated by flatc. After this change, it outputs
the JSON output:
"service": [
{ "name": "<service-name>",
"calls": [
{ "name": "<RPCCall-name>",
"request": <request-object>,
"response": <response-object> }
...
]
}
...
]
(optional attributes not shown)

Add RPC data to bfbs binary schema format

---

src/runtime/json_parser.c

(Extracted from PR #185)
After parsing a table or struct, ctx->end_loc is set to the current
value of buf, which is expected to be the end of the json data.
However the ctx->end_loc value is incorrect, because buf is not updated
after the call to the parser callback function.
Fix this in both flatcc_json_parser_table_as_root() and
flatcc_json_parser_struct_as_root().

Fix end_loc in json parser context

---

README.md
config/config.h
src/compiler/codegen_c_builder.c
src/compiler/codegen_c_reader.c

(Extracted from PR #185)
These 2 commits change how per-table file identifiers and extensions are generated:
- the file identifiers should not use `flatbuffers_identifier` because it prevents from including several schema definitions, use a direct string instead
- the per-table file extensions are not generated, let's add them similarly to file identifiers
changes in v2:
- fix documentation (README.md)

Fix per-table file identifiers and extensions

---

src/compiler/flatcc.c

When the file being compiled includes another one that does not exist,
the generation fails but the return code is 0:
user@host:$ echo 'include "unexistant_file.fbs";' > schema.fbs
user@host:$ flatcc schema.fbs
error reading included schema file: attributes.fbs
user@host:$ echo $?
0
In flatcc_parse_file(), the ret variable is initialized to -1 at the
beginning of the function, but modified to 0 when fb_parse() is called
with success. Subsequent "goto done" do not set back ret to -1, so the
return value is 0 when the file is not found.
Let's remove the use of ret in the fb_parse() test, and remove the
uneeded affectations of ret above.
Signed-off-by: Olivier Matz <olivier.matz@6wind.com>

fix flatcc return code on include failure

---

src/compiler/fileio.c
src/compiler/semantics.c

This fixes potential memory leaks that were detected by a quick run of cppcheck. In `fileio.c`, `memcpy()` will only copy from `prefix` to `path` if `prefix_len` is greater than 0, so copying from a potentially null pointer is avoided. In `semantics.c`, `index.len` is set accordingly based on `index.type` so that the former variable will always be initialized.

fix potential memory leaks in fileio.c and semantics.c

---

test/emit_test/emit_test.c
test/json_test/test_json.c
test/json_test/test_json_parser.c
test/json_test/test_json_printer.c
test/optional_scalars_test/optional_scalars_test.c

The build was failing on test functions missing prototypes.
Sample: 
```
FAILED: test/json_test/CMakeFiles/json_test_uq.dir/test_json.c.o
/Library/Developer/CommandLineTools/usr/bin/cc  -Itest/json_test/generated -I../../include -DFLATCC_REFLECTION=1 -Wstrict-prototypes -Wsign-conversion -Wconversion -std=c11 -pedantic -Wall -Wextra -Werror -g -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk -DFLATCC_JSON_PARSE_ALLOW_UNQUOTED=1 -MD -MT test/json_test/CMakeFiles/json_test_uq.dir/test_json.c.o -MF test/json_test/CMakeFiles/json_test_uq.dir/test_json.c.o.d -o test/json_test/CMakeFiles/json_test_uq.dir/test_json.c.o -c ../../test/json_test/test_json.c
../../test/json_test/test_json.c:142:20: error: this old-style function definition is not preceded by a prototype …
```

Remove strict prototypes from clang build

---

samples/monster/CMakeLists.txt
samples/reflection/CMakeLists.txt
test/emit_test/CMakeLists.txt
test/flatc_compat/CMakeLists.txt
test/json_test/CMakeLists.txt
test/load_test/CMakeLists.txt
test/monster_test/CMakeLists.txt
test/monster_test_concat/CMakeLists.txt
test/monster_test_cpp/CMakeLists.txt
test/monster_test_prefix/CMakeLists.txt
test/monster_test_solo/CMakeLists.txt
test/optional_scalars_test/CMakeLists.txt
test/reflection_test/CMakeLists.txt

When cmake is not on the path, the build would previously fail as it
hardcoded the name for the cmake binary, expecting to find it on the
path.  Use `CMAKE_COMMAND` instead to reference the cmake binary that
was used to configure the target.

build: repair the build where CMake is not on the path

---

include/flatcc/flatcc_json_parser.h
src/compiler/codegen_c_json_parser.c
src/compiler/codegen_c_json_printer.c
src/compiler/parser.c
src/compiler/semantics.c
src/runtime/json_parser.c

This uses the GNU extension of `__attribute__((__fallthrough__))` to
indicate the fallthrough paths.  The comments were introduced in GCC 7,
which introduced this attribute.  Adding this attribute additionally
silences the warning from clang.

Annotate fallthrough paths with attribute

---

src/compiler/semantics.c

Fix the following warning with clang.
```
[  7%] Building C object src/compiler/CMakeFiles/flatcc.dir/semantics.c.o
/Users/yamamoto/git/flatcc/src/compiler/semantics.c:1548:26: error: suggest
braces around initialization of subobject [-Werror,-Wmissing-braces]
fb_value_t index = { 0 };
^
{}
/Users/yamamoto/git/flatcc/src/compiler/semantics.c:1548:26: error: suggest
braces around initialization of subobject [-Werror,-Wmissing-braces]
fb_value_t index = { 0 };
^
{}
2 errors generated.
```

src/compiler/semantics.c: Fix a warning

---

src/runtime/verifier.c

If n = 0xFFFFFFFF then  n + 1 = 0.
end - base (unsigned value) is always greater then 0.
Finally the function test then value (buf + base)[0xFFFFFFFF] whish
crash.

Fix #221 Bad string lenght cause segmentation fault.

---

include/flatcc/flatcc_builder.h
include/flatcc/flatcc_json_parser.h
include/flatcc/flatcc_json_printer.h
src/compiler/codegen_c_json_parser.c
src/runtime/builder.c
src/runtime/json_parser.c
test/json_test/test_json.c
test/json_test/test_json_parser.c

When using the provided API to set multiple JSON-printer flags via `flatcc_json_printer_set_flags()`
some compilers and tools will give errors due to a bitwise operation on a signed integer type.
The provided flags are an enum and in C enums are signed (C99 6.4.4.3p2).
Since C doesn't mandate how to represent a negative signed value (one's complement/two's complement/..)
there is no portable way to do bit operations on signed values.
When a user wants to set multiple flags using bitwise OR with the provided flags this gives errors in the user code indicated by tools like clang-tidy. See the checker:
https://releases.llvm.org/10.0.0/tools/clasng/tools/extra/docs/clang-tidy/checks/hicpp-signed-bitwise.html
This PR proposes the use of unsigned int flags instead of an enum,
which avoids …

Use an unsigned type for public interface flags

---

include/flatcc/flatcc_json_parser.h
include/flatcc/portable/pattributes.h
src/compiler/codegen_c_json_parser.c
src/compiler/codegen_c_json_printer.c
src/compiler/parser.c
src/compiler/semantics.c
src/runtime/json_parser.c

Keeping pattributes in the portable library in case the usercode requires it.
The `fallthrough` define is no longer used internally and therefor not defined by default,
i.e PORTABLE_EXPOSE_ATTRIBUTES is not enabled by default.
No `implicit-fallthrough` build errors given in `./scripts/test.sh`
Fixes #247

Remove use of the `fallthrough` macro

---

src/compiler/codegen_c_reader.c
test/cgen_test/cgen_test.c
test/json_test/test_basic_parse.c
test/json_test/test_json.c

The diagnostics in Clang 15 is [stricter](https://releases.llvm.org/15.0.0/tools/clang/docs/ReleaseNotes.html#improvements-to-clang-s-diagnostics) and finds some issues.
- [-Werror,-Wstrict-prototypes]
Using a strict prototype for some main()'s in the test code.
- [-Werror,-Wunused-but-set-variable]
The variable 'present_id' is set but not used, so removed.
Some details: https://reviews.llvm.org/D122895

Enable to build using Clang 15

---

CMakeLists.txt

When working with Clang-cl on MSVC, the compiler ID is set to Clang while it expects flag in MSVC style.
So need to check also `CMAKE_CXX_SIMULATE_ID` and not only `CMAKE_C_COMPILER_ID`

Avoid false detection of Clang while using Clang-cl

---

.github/workflows/weekly.yml

gcc-9 was removed from Githubs macOS runner via https://github.com/actions/runner-images/issues/7136
This PR adds a prepare step which installs the required gcc version.
[Here](https://github.com/Nordix/flatcc/actions/runs/4828087072) is a forced run.

Install required gcc version in weekly CI for macOS

---

.github/workflows/weekly.yml

The weekly CI job that builds with Intel compilers now downloads and uses the [recommended keyfile](https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2023-2/apt.html) for Intels APT repository.
This should fix failing weekly runs.
We also replace the deprecated `apt-key` command with `gpg  --dearmor` which is generally recommended.
`apt-key` has security flaws and will be removed after Ubuntu 22.04.
This change follows [Intels installation guide](https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2023-2/apt.html).
Logs from a forced run of this PR can be found [here](https://github.com/Nordix/flatcc/actions/runs/6407705818/job/17395072085).

Update the apt key for Intel compilers in weekly CI

---

test/CMakeLists.txt
test/doublevec_test/CMakeLists.txt
test/doublevec_test/doublevec_test.c
test/doublevec_test/doublevec_test.fbs

I believe I have narrowed down the problem with #210 further. It appears to happen only for buffers with size.
I've made new doublevec_test with a very minimal schema and two test cases, one run without size prefix and one with.. the latter fails with "vector header out of range or unaligned".
ctest --verbose output:
```sh
20: doublevec table:
20: 00000000  04 00 00 00 f4 ff ff ff  04 00 00 00 00 00 00 00  |................|
20: 00000010  06 00 08 00 04 00                                 |......|
20: doublevec table with size:
20: 00000000  1a 00 00 00 08 00 00 00  00 00 00 00 f4 ff ff ff  |................|
20: 00000010  04 00 00 00 00 00 00 00  06 00 08 00 04 00        |..............|
20: running debug doublevec test
20: doublevec buffer failed to verify, got: vector header out of …
```

Minimal reproduction test case for misaligned vector of double

---

include/flatcc/portable/pattributes.h

This avoids warnings with clang-18+ e.g.
pprintint.h:256:6: error: [[]] attributes are a C23 extension [-Werror,-Wc23-extensions]

Check for C standard version >= 23 for [[__fallthrough__]]

---

src/cli/flatcc_cli.c
src/compiler/codegen_schema.c
src/compiler/flatcc.c

That change has two parts:
- use the option --outfile when generating binary schema
- avoid the removal of that created file

Fix use of --schema with --outfile

---

.github/workflows/weekly.yml

- Fix warning "Node.js 16 actions are deprecated"
Start using version `v2` of `actions-setup-cmake` which runs on Node.js 20.
- Add the latest `clang` and `gcc`,  the versions given by aminya/setup-cpp are:
- gcc-13.1
- clang-17.0.6
An [example](https://github.com/Nordix/flatcc/actions/runs/8268239669) run.
Note: an intermittent warning have been seen from the action `aminya/setup-cpp`, see https://github.com/aminya/setup-cpp/issues/234

CI: updates to Weekly build

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/weekly.yml

This PR updates our CI setup according to the secure software development best practices
recommended by the Open Source Security Foundation ([OpenSSF](https://openssf.org/)).
The overall goal is to strengthen the (supply chain) security posture.
The following changes are included:
- Pin the Github Action dependencies to hash.
When developing a CI workflow, it's common to version-pin dependencies (i.e. `actions/checkout@v4`). However, version tags are mutable, so a malicious attacker could overwrite a version tag to point to a malicious or vulnerable commit instead.
Pinning workflow dependencies by hash ensures the dependency is immutable and its behavior is guaranteed.
https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
- Set the default permission for CI …

Improve Github repository security

---

.github/workflows/weekly.yml

The macOS 11 runner image will soon be removed (2024-06-24) according to [github.blog](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal), so lets replace `macos-11` with `macos-12`. The gcc versions used in the CI job `macos-gcc` are also lifted since `gcc-9` wont run on `macos-12` (due to macosx-version-min).
This PR also adds the latest release of `clang` to CI.
A weekly run:
https://github.com/Nordix/flatcc/actions/runs/9172372095

Replace `macos-11` runner in CI since it's deprecated

---

.github/workflows/ci.yml
.github/workflows/weekly.yml

Split the CI jobs for testing Mac to run on both "old" x86 runners and the new M1 runner.
The pre-installed gcc 13.3 (brew package `gcc-13`) only seems to work with an older MacOSX.sdk version than the [default](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#xcode) in a macos-12 runner.
Lets update to `gcc-14` which has been corrected to be able to use any SDK version.
This PR also adds a check if the compiler is already installed, which silences a warning.
Weekly run:
https://github.com/Nordix/flatcc/actions/runs/9413941834

Separate CI jobs for macOS on x86

---

.github/workflows/weekly.yml

Since gcc@11 suddenly started to fail on runner `macos-14` due to a non-matching default Xcode version;
lets only use supported versions of GCC in the macOS weekly runs.
These GCC versions are more likely verified to work fine on runners.
Only the 3 latest versions of GCC are supported, i.e. GCC 12, 13 and 14 according to
https://github.com/actions/runner-images/issues/10213 and https://github.com/actions/runner-images#software-and-image-support .
Manual run: https://github.com/Nordix/flatcc/actions/runs/10418446489

Use supported GCC versions in weekly CI for macOS

---

.github/workflows/weekly.yml

Investigated the issue with the weekly CI runs failing and created this issue:  https://github.com/aminya/setup-cpp/issues/295
Lets revert this version to the older version that used a more accepting client while downloading llvm packages.
Maybe the issue is temporary but lets use the older version until I can make sure, or the issue is fixed in setup-cpp.
Reverts dvidelabs/flatcc#294

Revert "Bump aminya/setup-cpp from 0.39.0 to 0.41.0"

---

external/hash/str_set.c

take length of keys in the str_set hash into account so keys which are perfect sub-strings do not match incorrectly

consider length of string keys

---

src/compiler/codegen_c_builder.c
src/compiler/codegen_c_reader.c

Remove two GCC (tested on 13.2.0) warnings from code.
I believe if accepted would be good also to put to the pregenerated ones (in `include/flatcc/reflection/`), but I didn't do that as I supposed maintainer takes usually care of that :-) (can add to PR if needed!)
Example output I see:
```
/home/foo/bar/generated/flatbuffers_common_builder.h: In function 'flatbuffers_char_array_copy_from_pe':
/home/foo/bar/generated/flatbuffers_common_builder.h:341:3: error: this 'for' clause does not guard... [-Werror=misleading-indentation]
341 |   for (i = 0; i < n; ++i) N ## _copy_from_pe(&p[i], &p2[i]); return p; }\
|   ^~~
/home/foo/bar/generated/flatbuffers_common_builder.h:360:1: note: in expansion of macro '__flatbuffers_define_fixed_array_primitives'
360 | __ ## NS ## …
```

Remove a few misleading-indentation warnings

---

include/flatcc/flatcc_endian.h
include/flatcc/portable/pstdint.h

Tinkered a bit to allow reading of flatbuffers without stdlib, obviously you'll need to define the stdint types and `#defines` in your build environment.
Very much a new contributor to open source so apologies in advance

flatbuffer reading support for windows kernelland

---

include/flatcc/flatcc_verifier.h

https://github.com/dvidelabs/flatcc/blob/b50e43dd1269b91203be8b5b185923d841c93e70/src/runtime/verifier.c#L511
As flagged by `clang-tidy`:
https://clang.llvm.org/extra/clang-tidy/checks/readability/inconsistent-declaration-parameter-name.html
---
The alternative is to change the name in the definition, which requires a bigger diff. The function is short enough that there's not much difference either way, though.

Sync flatcc_verify_typed_buffer_header_with_size parameter name vs. definition

---

src/runtime/CMakeLists.txt

Otherwise, include directories are not propagated to targets calling `target_link_libraries()`.

runtime/CMakeLists.txt: Use target_include_directories
